"""added repeat_month_day column to habits table

Revision ID: 42f9e1a7377a
Revises: 4d07a636b32f
Create Date: 2025-06-12 23:06:27.665848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42f9e1a7377a'
down_revision = '4d07a636b32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_month_day', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_column('repeat_month_day')

    # ### end Alembic commands ###
