"""empty message

Revision ID: 81ec267334cb
Revises: 9022e299875d
Create Date: 2025-06-10 19:56:12.859745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ec267334cb'
down_revision = '9022e299875d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('habits', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['uid'])

    # ### end Alembic commands ###
