"""empty message

Revision ID: 99f2237b5308
Revises: 99d5b4676939
Create Date: 2025-06-20 18:47:13.132384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f2237b5308'
down_revision = '99d5b4676939'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('_email_uc', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('_email_uc', type_='unique')

    # ### end Alembic commands ###
